services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - inception
    restart: unless-stopped
    volumes:
      - wordpress_data:/var/www/html

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    ports:
      - "3306:3306"
    restart: unless-stopped

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/yfang/data/wordpress
      o: bind
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/yfang/data/mariadb
      o: bind